name: assessmentFront
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Clean folder
        uses: appleboy/ssh-action@master
        with:                    
            host: 3.140.189.245
            username: ubuntu
            key: "${{ secrets.SSH_PRIVATE_KEY_DEV }}"
            script: |                      
              sudo rm -Rf /var/www/assessmentFront
              sudo mkdir /var/www/assessmentFront
              sudo chmod -Rf 777 /var/www/assessmentFront
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/assessmentFront/
          remote_host: 3.140.189.245
          remote_user: ubuntu
          remote_key: '${{ secrets.SSH_PRIVATE_KEY_DEV }}'

      - name: deploy to server and application start
        uses: appleboy/ssh-action@master
        with:                    
            host: 3.140.189.245
            username: ubuntu
            key: "${{ secrets.SSH_PRIVATE_KEY_DEV }}"
            script: |                      
              cd /var/www/assessmentFront/
              # cd /var/www/assessmentFront/ && npm install              
              # cd /var/www/assessmentFront/ && pm2 stop assessmentFront && pm2 delete assessmentFront && pm2 start npm --name "assessmentFront" -- start
